[project]
name = "mycelian"
version = "1.12.2"
description = "Mycelian is a custom alert and browser source tool for Twitch streamers."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11.11",
    "configparser>=7.1.0",
    "cryptography>=43.0.0",
    "firebase-admin>=6.6.0",
    "flask>=3.1.0",
    "flask-socketio>=5.5.1",
    "nicegui>=3.12.1,<4",
    "packaging>=24.2",
    "psutil>=6.1.1",
    "python-socketio>=5.11.0",
    "pyperclip>=1.8.2",
    "python-engineio>=4.11.2",
    "pywebview>=6.2.1",
    "requests-oauthlib>=2.0.0",
    "requests>=2.32.3",
    "spotipy>=2.26.0",
    "twitchapi>=4.5.0",
    "websocket-client>=1.8.0",
    "pyinstaller>=6.14.1",
    "eventlet>=0.40.0",
    "gevent>=25.5.1",
    "pynput>=1.7.7",
    "pycaw>=20240210; sys_platform == 'win32'",
    "pulsectl>=24.12.0; sys_platform == 'linux'",
    "pyobjc>=11.1; sys_platform == 'darwin'",
    "pycaw>=20240210",
    "pulsectl>=24.12.0",
    "psnawp==3.0.1",
    "pytz>=2025.2",
    "pillow>=10.0.0",
    "obsws-python>=1.8.0",
    "discord-py>=2.7.1",
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["modules*"]
exclude = ["assets*", "templates*", "logs*", "docs*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.html", "*.css", "*.js"]
