"""One-off generator for assets/ff7/*_names_en.json (kernel weapon index order 0-127)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

WEAPONS_EN = [
    "Buster Sword",
    "Mythril Saber",
    "Hardedge",
    "Butterfly Edge",
    "Enhance Sword",
    "Organics",
    "Crystal Sword",
    "Force Stealer",
    "Rune Blade",
    "Murasame",
    "Nail Bat",
    "Yoshiyuki",
    "Apocalypse",
    "Heaven's Cloud",
    "Ragnarok",
    "Ultima Weapon",
    "Leather Glove",
    "Metal Knuckle",
    "Mythril Claw",
    "Grand Glove",
    "Tiger Fang",
    "Diamond Knuckle",
    "Dragon Claw",
    "Crystal Glove",
    "Motor Drive",
    "Platinum Fist",
    "Kaiser Knuckle",
    "Work Glove",
    "Powersoul",
    "Master Fist",
    "God's Hand",
    "Premium Heart",
    "Gatling Gun",
    "Assault Gun",
    "Cannon Ball",
    "Atomic Scissors",
    "Heavy Vulcan",
    "Chainsaw",
    "Microlaser",
    "A.M Cannon",
    "W Machine Gun",
    "Drill Arm",
    "Solid Bazooka",
    "Rocket Punch",
    "Enemy Launcher",
    "Pile Banger",
    "Max Ray",
    "Missing Score",
    "Mythril Clip",
    "Diamond Pin",
    "Silver Barrette",
    "Gold Barrette",
    "Ruby Barrette",
    "Emerald Barrette",
    "Diamond Barrette",
    "Crystal Barrette",
    "Magic Comb",
    "Plus Barrette",
    "Centclip",
    "Hairpin",
    "Seraph Comb",
    "Behemoth Horn",
    "Spring Gun Clip",
    "Limited Moon",
    "Guard Stick",
    "Mythril Rod",
    "Full Metal Staff",
    "Striking Staff",
    "Prism Staff",
    "Aurora Rod",
    "Wizard Staff",
    "Wizer Staff",
    "Fairy Tale",
    "Umbrella",
    "Princess Guard",
    "",
    "",
    "",
    "",
    "",
    "4-point Shuriken",
    "Boomerang",
    "Pinwheel",
    "Razor Ring",
    "Hawkeye",
    "Crystal Cross",
    "Wind Slash",
    "Twin Viper",
    "Spiral Shuriken",
    "Superball",
    "Magic Shuriken",
    "Rising Sun",
    "Oritsuru",
    "Conformer",
    "",
    "",
    # 96–127: Vincent (13) + padding, then Cid (14) + padding (KERNEL order; Cait uses other indices).
    "Quicksilver",
    "Shotgun",
    "Shortbarrel",
    "Lariat",
    "Winchester",
    "Peacemaker",
    "Buntline",
    "Long Barrel R",
    "Silver Rifle",
    "Sniper CR",
    "Supershot ST",
    "Outsider",
    "Death Penalty",
    "",
    "",
    "Spear",
    "Slash Lance",
    "Trident",
    "Mast Ax",
    "Partisan",
    "Viper Halberd",
    "Javelin",
    "Grow Lance",
    "Mop",
    "Dragoon Lance",
    "Scimitar",
    "Flayer",
    "Spirit Lance",
    "Venus Gospel",
    "",
    "",
    "",
]

ARMOR_EN = [
    "Bronze Bangle",
    "Iron Bangle",
    "Toy Soldier",
    "Wrist Band",
    "Silver Bangles",
    "Mystery Vest",
    "Platinum Bangle",
    "Carbon Bangle",
    "Four Slots",
    "Warrior Bangle",
    "Shinra Beta",
    "Four Bracelets",
    "Aurora Armlet",
    "Bolt Armlet",
    "Dragon Armlet",
    "Minerva Band",
    "Escort Guard",
    "Precious Watch",
    "Chocobo Armlet",
    "Aegis Armlet",
    "Fire Armlet",
    "Fourth Bracelet",
    "Diamond Bangle",
    "Crystal Bangle",
    "Wizard Bracelet",
    "Adaman Bangle",
    "Gigas Armlet",
    "Imperial Guard",
    "Ziedrich",
    "Edincoat",
    "",
    "",
]

ACCESSORY_EN = [
    "Power Wrist",
    "Protect Vest",
    "Earring",
    "Talisman",
    "Choco Feather",
    "Amulet",
    "Champion Belt",
    "Poison Ring",
    "Tough Ring",
    "Circlet",
    "Star Pendant",
    "Silver Glasses",
    "Headband",
    "Fairy Ring",
    "Jem Ring",
    "White Cape",
    "Sprint Shoes",
    "Peace Ring",
    "Ribbon",
    "Fire Ring",
    "Ice Ring",
    "Bolt Ring",
    "Tetra Elemental",
    "Safety Bit",
    "Fury Ring",
    "Curse Ring",
    "Protect Ring",
    "Cat's Bell",
    "Reflect Ring",
    "Water Ring",
    "HypnoCrown",
    "Sneak Glove",
]


def main() -> None:
    assert len(WEAPONS_EN) == 128, len(WEAPONS_EN)
    assert len(ARMOR_EN) == 32, len(ARMOR_EN)
    assert len(ACCESSORY_EN) == 32, len(ACCESSORY_EN)
    out = ROOT / "assets" / "ff7"
    (out / "weapon_names_en.json").write_text(
        json.dumps({str(i): WEAPONS_EN[i] for i in range(128)}, indent=2, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )
    (out / "armor_names_en.json").write_text(
        json.dumps({str(i): ARMOR_EN[i] for i in range(32)}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (out / "accessory_names_en.json").write_text(
        json.dumps({str(i): ACCESSORY_EN[i] for i in range(32)}, indent=2, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )
    print("Wrote weapon, armor, accessory name JSON under", out)


if __name__ == "__main__":
    main()
