"""
Dump English kernel command (32) and attack (128) name tables from a running ff7_en.exe
into assets/ff7/battle_log_names_en.json. Same layout as ff7-ultima / ff7-lib read_command_names
and read_attack_names.

Usage (from repo root, with Final Fantasy VII running and visible in Task Manager):
  python tools/dump_battle_log_names.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from modules.game_hooks.ff7_hook import FF7Hook  # noqa: E402


def main() -> int:
    hook = FF7Hook()
    ok, err = hook.ensure_attached()
    if not ok:
        print(f"Not attached: {err or 'unknown'}", file=sys.stderr)
        return 1
    cmds = hook._read_kernel_section_strings(8, 32)  # noqa: SLF001
    atks = hook._read_kernel_section_strings(9, 128)  # noqa: SLF001
    if not cmds and not atks:
        print(
            "No strings read. Is ff7_en.exe running and is the hook attached?",
            file=sys.stderr,
        )
        return 1
    out = {
        "_meta": "Generated by tools/dump_battle_log_names.py (retail kernel RAM).",
        "commands": {str(i): s for i, s in enumerate(cmds) if (s or "").strip()},
        "attacks_128": {str(i): s for i, s in enumerate(atks) if (s or "").strip()},
    }
    path = ROOT / "assets" / "ff7" / "battle_log_names_en.json"
    path.write_text(
        json.dumps(out, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {path} ({len(cmds)} commands, {len(atks)} attack slots)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
